### ISSUE TITLE
Cooperative Lane change plugin does not generate a trajectory

### ISSUE THREAD

**Issue by saina-ramyar** [usdot-fhwa-stol/carma-platform#1910] opened 2022-08-25 14:31 UTC
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

In a route that includes a lane change, a lane change trajectory is not generated so the vehicle does not move.
### Carma version where this issue was discovered
develop

### Expected behavior
Lane change trajectory is generated.
### Actual behavior

Lane change trajectory is not generated
### Steps to reproduce the actual behavior

1. start carma platform
2. select a route with a lanechange
3. engage

**Comment by JonSmet** [comment] 2022-08-25 17:25
Duplicate of issue #1908.

**Closed by JonSmet** 2022-08-25 17:25 UTC
