### ISSUE TITLE
Lexus AVT Vimba Camera (left) IP Address is incorrect *****

### ISSUE THREAD

**Issue by lewisid** [usdot-fhwa-stol/carma-platform#1077] opened 2021-02-08 15:39 UTC
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

When running Carma on the blue Lexus, it was discovered that the IP address of the avt_vimba_camera in the driver.launch folder did not match what was specified for the vehicle. This prevented the system from accessing information from the camera.
### Carma version where this issue was discovered

release/vanden-plas
### Expected behavior
The IP address in the file would match that of the vehicle and the avt_vimba_camera information would be accessible.
### Actual behavior

See the description above.
### Steps to reproduce the actual behavior

1. Run the vanden-plas candidate docker image and enter carma config edit.
2. Navigate to the config folder and open the driver.launch file.
3. Scroll downward towards the IP address settings for the left avt_vimba_camera. The IP address will be listed as 192.168.30.10, when the IP address for the vehicle is actually 192.168.40.1.

**Comment by msmcconnell** [comment] 2021-02-08 21:55
Duplicate of #1070

**Closed by msmcconnell** 2021-02-08 21:55 UTC
