### ISSUE TITLE
Ford Fusion: SSC Issues

### ISSUE THREAD

**Issue by maefromm** [usdot-fhwa-stol/carma-platform#1141] opened 2021-03-11 14:36 UTC
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Opened AStuff Ticket #3793 with the following issues description: 
Good morning, Cullen and Ben. 
I have received reports on SSC errors/faults on the Ford Fusion quite frequently. Could you help us address the SSC issues we’re having on Ford? 
**Yesterday from Sudhakar:** 
1.       We are getting a lot of SSC faults on Ford Fusion multiple times in a trip. We also noticed that there is SSC log message in the CARMA terminal that indicated that there is a new firmware. Can we do this update on the air or how should we do this? Attached is a screenshot provided in the foler below: “20210309_SSCFault_NewFirmwareNotification”
**Today from Misheel:** 
2.       At first I thought this was not related to ssc error, as I thought UI is reporting ssc failed when everything failed because of wmbroadcaster not being able to find map.But as it is happening pretty frequently, I thought it was best to have it checked by Astuff. See rosbag “fushion-ssc-err-at-start.active” and “ssc-error-snippet” text log file provided in the folder below.
3.        There is another type of ssc error I have a rosbag for (that happens in mid-run), but its bag is big, so it is taking time in uploading to drive. 
4.       There a silent ssc error as well that occurs: fushion-silent-ssc.bag.active
 
https://drive.google.com/drive/folders/1bon2VSe4EGHj33PpFgslt_ayPrdGuMLw?usp=sharing

### Carma version where this issue was discovered

Vanden Plas Candidate Release 

### Expected behavior
Should not recieve any frequent SSC faults. 

### Actual behavior

See above 

### Steps to reproduce the actual behavior

See above

**Comment by msmcconnell** [comment] 2021-03-11 14:38
@maefromm This is a duplicate of https://github.com/usdot-fhwa-stol/carma-platform/issues/1093

**Closed** 2021-03-15 13:00 UTC
Labels: anomaly
